import string
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

PUNCTUATIONS = string.punctuation
STOPWORDS = set(stopwords.words('english'))
EMOTICONS = {
    u":-\)":"Happy face smiley",
    u":\)":"Happy face smiley",
    u":-\]":"Happy face smiley",
    u":\]":"Happy face smiley",
    u":-3":"Happy face smiley",
    u":3":"Happy face smiley",
    u":->":"Happy face smiley",
    u":>":"Happy face smiley",
    u"8-\)":"Happy face smiley",
    u":o\)":"Happy face smiley",
    u":-\}":"Happy face smiley",
    u":\}":"Happy face smiley",
    u":c\)":"Happy face smiley",
    u":\^\)":"Happy face smiley",
    u"=\]":"Happy face smiley",
    u"=\)":"Happy face smiley",
    u":-\)\)":"Happy face smiley",
    u":-D":"Laughing",
    u":D":"Laughing",
    u"8-D":"Laughing",
    u"8D":"Laughing",
    u"X-D":"Laughing",
    u"XD":"Laughing",
    u"=D":"Laughing",
    u"=3":"Laughing",
    u"B\^D":"Laughing",
    u":-\(":"Sad face frown",
    u":-\(":"Sad face frown",
    u":\(":"Sad face frown",
    u":-c":"Sad face frown",
    u":c":"Sad face frown",
    u":-<":"Sad face frown",
    u":<":"Sad face frown",
    u":-\[":"Sad face frown",
    u":\[":"Sad face frown",
    u":-\|\|":"Sad face frown",
    u">:\[":"Sad face frown",
    u":\{":"Sad face frown",
    u":@":"Sad face frown",
    u">:\(":"Sad face frown",
    u":'-\(":"Crying",
    u":'\(":"Crying",
    u":'-\)":"Tears of happiness",
    u":'\)":"Tears of happiness",
    u"D-':":"Horror",
    u"D:<":"Disgust",
    u"D:":"Sadness",
    u"D8":"Great dismay",
    u"D;":"Great dismay",
    u"D=":"Great dismay",
    u"DX":"Great dismay",
    u":-O":"Surprised",
    u":O":"Surprised",
    u":-o":"Surprised",
    u":o":"Surprised",
    u":-0":"Surprised",
    u"8-0":"Yawn",
    u">:O":"Yawn",
    u":-\*":"Kiss",
    u":\*":"Kiss",
    u":X":"Kiss",
    u";-\)":"Wink or smirk",
    u";\)":"Wink or smirk",
    u"\*-\)":"Wink or smirk",
    u"\*\)":"Wink or smirk",
    u";-\]":"Wink or smirk",
    u";\]":"Wink or smirk",
    u";\^\)":"Wink or smirk",
    u":-,":"Wink or smirk",
    u";D":"Wink or smirk",
    u":-P":"Tongue sticking out",
    u":P":"Tongue sticking out",
    u"X-P":"Tongue sticking out",
    u"XP":"Tongue sticking out",
    u":-Þ":"Tongue sticking out",
    u":Þ":"Tongue sticking out",
    u":b":"Tongue sticking out",
    u"d:":"Tongue sticking out",
    u"=p":"Tongue sticking out",
    u">:P":"Tongue sticking out",
    u":-/":"Skeptical or annoyed",
    u":/":"Skeptical or annoyed",
    u":-[.]":"Skeptical or annoyed",
    u">:/":"Skeptical or annoyed",
    u"=/":"Skeptical or annoyed",
    u":L":"Skeptical or annoyed",
    u"=L":"Skeptical or annoyed",
    u":S":"Skeptical or annoyed",
    u":-\|":"Straight face",
    u":\|":"Straight face",
    u":$":"Embarrassed or blushing",
    u":-x":"Sealed lips",
    u":x":"Sealed lips",
    u":-#":"Sealed lips",
    u":#":"Sealed lips",
    u":-&":"Sealed lips",
    u":&":"Sealed lips",
    u"O:-\)":"Angel",
    u"<:-\|":"Dump",
    u"\(T_T\) \(;_;\)":"Sad or Crying",
    u"\(;_;":"Sad or Crying",
    u"\(;_:\)":"Sad or Crying",
    u"\(;O;\)":"Sad or Crying",
    u"\(:_;\)":"Sad or Crying",
    u"\(ToT\)":"Sad or Crying",
    u";_;":"Sad or Crying",
    u";-;":"Sad or Crying",
    u";n;":"Sad or Crying",
    u"Q\.Q":"Sad or Crying",
    u"T\.T":"Sad or Crying",
    u"QQ":"Sad or Crying",
    u"Q_Q":"Sad or Crying",
    u"\(-\.-\)":"Shame",
    u"\(-_-\)":"Shame",
    u"\(?_?\)":"Confusion",
    u":O o_O":"Surprised",
    u"o_0":"Surprised",
    u"o\.O":"Surprised"
}
POS_EMOT = [
    'Happy face smiley', 'Wink or smirk', 'Tears of happiness', 'Laughing',
    'Suprised', 'Kiss', 'Tongue sticking out', 'Angel'
    ]
NEG_EMOT = [
    'Sad face frown', 'Crying', 'Horror', 'Disgust', 'Sadness', 'Yawn',
    'Great dismay', 'Skeptical or annoyed', 'Surprised', 'Straight face',
    'Sealed lips', 'Dump', 'Embarrassed or blushing', 'Sad or Crying',
    'Shame', 'Confusion', 'Worried'
    ]

POS_EMOJI = [
    '\U0001F601', '\U0001F602', '\U0001F603', '\U0001F604', '\U0001F605',
    '\U0001F606', '\U0001F609', '\U0001F60A', '\U0001F60B', '\U0001F60C',
    '\U0001F60D', '\U0001F60F', '\U0001F618', '\U0001F61A', '\U0001F61C',
    '\U0001F61D', '\U0001F64C', '\U0001F600', '\U0001F607', '\U0001F60E',
    '\U0001F525', '\U0001F44D', '\U0001F4AA', '\U0001F4AF'
    ]
NEG_EMOJI = [
    '\U0001F612', '\U0001F613', '\U0001F614', '\U0001F616', '\U0001F61E',
    '\U0001F620', '\U0001F621', '\U0001F622', '\U0001F623', '\U0001F624',
    '\U0001F625', '\U0001F628', '\U0001F629', '\U0001F62A', '\U0001F62B',
    '\U0001F62D', '\U0001F630', '\U0001F631', '\U0001F632', '\U0001F633',
    '\U0001F635', '\U0001F637', '\U0001F645', '\U0001F610', '\U0001F611',
    '\U0001F615', '\U0001F61F', '\U0001F626', '\U0001F627', '\U0001F4A9', 
    '\U0001F44E'
    ]