import re
import string
import nltk
from nltk.corpus import stopwords

import emot
from emot.emo_unicode import EMOTICONS_EMO

nltk.download('stopwords')

PUNCTUATIONS = string.punctuation
STOPWORDS = set(stopwords.words('english'))
EMOTICONS = {
    u":-\)":"Happy face smiley",
    u":\)":"Happy face smiley",
    u":-\]":"Happy face smiley",
    u":\]":"Happy face smiley",
    u":-3":"Happy face smiley",
    u":3":"Happy face smiley",
    u":->":"Happy face smiley",
    u":>":"Happy face smiley",
    u"8-\)":"Happy face smiley",
    u":o\)":"Happy face smiley",
    u":-\}":"Happy face smiley",
    u":\}":"Happy face smiley",
    u":c\)":"Happy face smiley",
    u":\^\)":"Happy face smiley",
    u"=\]":"Happy face smiley",
    u"=\)":"Happy face smiley",
    u":-\)\)":"Happy face smiley",
    u":-D":"Laughing",
    u":D":"Laughing",
    u"8-D":"Laughing",
    u"8D":"Laughing",
    u"X-D":"Laughing",
    u"XD":"Laughing",
    u"=D":"Laughing",
    u"=3":"Laughing",
    u"B\^D":"Laughing",
    u":-\(":"Sad face frown",
    u":-\(":"Sad face frown",
    u":\(":"Sad face frown",
    u":-c":"Sad face frown",
    u":c":"Sad face frown",
    u":-<":"Sad face frown",
    u":<":"Sad face frown",
    u":-\[":"Sad face frown",
    u":\[":"Sad face frown",
    u":-\|\|":"Sad face frown",
    u">:\[":"Sad face frown",
    u":\{":"Sad face frown",
    u":@":"Sad face frown",
    u">:\(":"Sad face frown",
    u":'-\(":"Crying",
    u":'\(":"Crying",
    u":'-\)":"Tears of happiness",
    u":'\)":"Tears of happiness",
    u"D-':":"Horror",
    u"D:<":"Disgust",
    u"D:":"Sadness",
    u"D8":"Great dismay",
    u"D;":"Great dismay",
    u"D=":"Great dismay",
    u"DX":"Great dismay",
    u":-O":"Surprised",
    u":O":"Surprised",
    u":-o":"Surprised",
    u":o":"Surprised",
    u":-0":"Surprised",
    u"8-0":"Yawn",
    u">:O":"Yawn",
    u":-\*":"Kiss",
    u":\*":"Kiss",
    u":X":"Kiss",
    u";-\)":"Wink or smirk",
    u";\)":"Wink or smirk",
    u"\*-\)":"Wink or smirk",
    u"\*\)":"Wink or smirk",
    u";-\]":"Wink or smirk",
    u";\]":"Wink or smirk",
    u";\^\)":"Wink or smirk",
    u":-,":"Wink or smirk",
    u";D":"Wink or smirk",
    u":-P":"Tongue sticking out",
    u":P":"Tongue sticking out",
    u"X-P":"Tongue sticking out",
    u"XP":"Tongue sticking out",
    u":-Þ":"Tongue sticking out",
    u":Þ":"Tongue sticking out",
    u":b":"Tongue sticking out",
    u"d:":"Tongue sticking out",
    u"=p":"Tongue sticking out",
    u">:P":"Tongue sticking out",
    u":-/":"Skeptical or annoyed",
    u":/":"Skeptical or annoyed",
    u":-[.]":"Skeptical or annoyed",
    u">:/":"Skeptical or annoyed",
    u"=/":"Skeptical or annoyed",
    u":L":"Skeptical or annoyed",
    u"=L":"Skeptical or annoyed",
    u":S":"Skeptical or annoyed",
    u":-\|":"Straight face",
    u":\|":"Straight face",
    u":$":"Embarrassed or blushing",
    u":-x":"Sealed lips",
    u":x":"Sealed lips",
    u":-#":"Sealed lips",
    u":#":"Sealed lips",
    u":-&":"Sealed lips",
    u":&":"Sealed lips",
    u"O:-\)":"Angel",
    u"<:-\|":"Dump",
    u"\(T_T\) \(;_;\)":"Sad or Crying",
    u"\(;_;":"Sad or Crying",
    u"\(;_:\)":"Sad or Crying",
    u"\(;O;\)":"Sad or Crying",
    u"\(:_;\)":"Sad or Crying",
    u"\(ToT\)":"Sad or Crying",
    u";_;":"Sad or Crying",
    u";-;":"Sad or Crying",
    u";n;":"Sad or Crying",
    u"Q\.Q":"Sad or Crying",
    u"T\.T":"Sad or Crying",
    u"QQ":"Sad or Crying",
    u"Q_Q":"Sad or Crying",
    u"\(-\.-\)":"Shame",
    u"\(-_-\)":"Shame",
    u"\(?_?\)":"Confusion",
    u":O o_O":"Surprised",
    u"o_0":"Surprised",
    u"o\.O":"Surprised"
}
POS_EMOT = [
    r'.*(happy).*', r'.*(laugh).*', r'.*(happiness).*', r'.*(surprise).*',
    r'.*(kiss).*', r'.*(wink).*', r'.*(tongue)(?!-tied).*', r'.*(angel).*',
    r'.*(cool).*', r'.*(party).*', r'.*(baby).*', r'.*(sleeping).*',
    r'.*(confused).*', r'.*(ultraman).*', r'.*(joyful).*', r'.*(waving).*',
    r'.*(excited).*', r'.*(amazed).*', r'.*(headphones).*', r'.*(eyeglasses).*'
]
NEG_EMOT = [
    r'.*(sad).*', r'.*(crying).*', r'.*(horror).*', r'.*(disgust).*',
    r'.*(dismay).*', r'.*(shock).*', r'.*(yawn).*', r'.*(skeptical).*',
    r'.*(straight face).*', r'.*(embarrassed).*', r'.*(sealed lips).*',
    r'.*(evil).*', r'.*(bored).*', r'.*(sick).*', r'.*(dump).*',
    r'.*(troubled).*', r'.*(shame).*', r'.*(tired).*', r'.*(worried).*',
    r'.*(dissatisfied).*', r'.*(snubbed).*', r'.*(nervous).*', r'.*(confusion).*'
]

POS_EMOJI = [
    '\U0001F601', '\U0001F602', '\U0001F603', '\U0001F604', '\U0001F605',
    '\U0001F606', '\U0001F609', '\U0001F60A', '\U0001F60B', '\U0001F60C',
    '\U0001F60D', '\U0001F60F', '\U0001F618', '\U0001F61A', '\U0001F61C',
    '\U0001F61D', '\U0001F64C', '\U0001F600', '\U0001F607', '\U0001F60E',
    '\U0001F525', '\U0001F44D', '\U0001F4AA', '\U0001F4AF'
    ]
NEG_EMOJI = [
    '\U0001F612', '\U0001F613', '\U0001F614', '\U0001F616', '\U0001F61E',
    '\U0001F620', '\U0001F621', '\U0001F622', '\U0001F623', '\U0001F624',
    '\U0001F625', '\U0001F628', '\U0001F629', '\U0001F62A', '\U0001F62B',
    '\U0001F62D', '\U0001F630', '\U0001F631', '\U0001F632', '\U0001F633',
    '\U0001F635', '\U0001F637', '\U0001F645', '\U0001F610', '\U0001F611',
    '\U0001F615', '\U0001F61F', '\U0001F626', '\U0001F627', '\U0001F4A9', 
    '\U0001F44E'
    ]

SLANG = {
    'AFAIK': 'As Far As I Know',
    'AFK': 'Away From Keyboard',
    'ASAP': 'As Soon As Possible',
    'ATK': 'At The Keyboard',
    'ATM': 'At The Moment',
    'A3': 'Anytime, Anywhere, Anyplace',
    'BAK': 'Back At Keyboard',
    'BBL': 'Be Back Later',
    'BBS': 'Be Back Soon',
    'BFN': 'Bye For Now',
    'B4N': 'Bye For Now',
    'BRB': 'Be Right Back',
    'BRT': 'Be Right There',
    'BTW': 'By The Way',
    'B4': 'Before',
    'CU': 'See You',
    'CUL8R': 'See You Later',
    'CYA': 'See You',
    'FAQ': 'Frequently Asked Questions',
    'FC': 'Fingers Crossed',
    'FWIW': "For What It's Worth",
    'FYI': 'For Your Information',
    'GAL': 'Get A Life',
    'GG': 'Good Game',
    'GN': 'Good Night',
    'GMTA': 'Great Minds Think Alike',
    'GR8': 'Great!',
    'G9': 'Genius',
    'IC': 'I See',
    'ICQ': 'I Seek you',
    'ILU': 'ILU: I Love You',
    'IMHO': 'In My Honest Opinion',
    'IMO': 'In My Opinion',
    'IOW': 'In Other Words',
    'IRL': 'In Real Life',
    'KISS': 'Keep It Simple, Stupid',
    'LDR': 'Long Distance Relationship',
    'LMAO': 'Laugh My Aaa Off',
    'LOL': 'Laughing Out Loud',
    'LTNS': 'Long Time No See',
    'L8R': 'Later',
    'MTE': 'My Thoughts Exactly',
    'M8': 'Mate',
    'NRN': 'No Reply Necessary',
    'OIC': 'Oh I See',
    'PITA': 'Pain In The Ass',
    'PRT': 'Party',
    'PRW': 'Parents Are Watching',
    'ROFL': 'Rolling On The Floor Laughing',
    'ROFLOL': 'Rolling On The Floor Laughing Out Loud',
    'ROTFLMAO': 'Rolling On The Floor Laughing My Ass Off',
    'SK8': 'Skate',
    'STATS': 'Your sex and age',
    'ASL': 'Age Sex Location',
    'THX': 'Thank You',
    'TTFN': 'Ta-Ta For Now!',
    'TTYL': 'Talk To You Later',
    'U': 'You',
    'U2': 'You Too',
    'U4E': 'Yours For Ever',
    'WB': 'Welcome Back',
    'WTF': 'What The Fuck',
    'WTG': 'Way To Go!',
    'WUF': 'Where Are You From?',
    'W8': 'Wait'
    }