import re
import string
import nltk
from nltk.corpus import stopwords

import emot
from emot.emo_unicode import EMOTICONS_EMO

nltk.download('stopwords')

PUNCTUATIONS = string.punctuation
STOPWORDS = set(stopwords.words('english'))
EMOTICONS = {
    ":(-|‑)?(\)+|\])":"Happy face or very happy face or smiley",
    ":(-|‑)?(3|>)":"Happy face smiley",
    "(8-|:o)\)":"Happy face smiley",
    ":(-|‑)?\}":"Happy face smiley",
    ":(c|\^)?\)":"Happy face smiley",
    "=(\)|\])":"Happy face smiley",
    "(:|8|X)[-|‑]?D":"Laughing, big grin or laugh with glasses",
    "=(D|3)":"Laughing, big grin or laugh with glasses",
    "B\^D":"Laughing, big grin or laugh with glasses",
    ":(-|‑)?(\(|c|<|\[)":"Frown, sad, angry or pouting",
    ":-\|\|":"Frown, sad, angry or pouting",
    ">:(\(|\[)":"Frown, sad, angry or pouting",
    ":-(\{|@)":"Frown, sad, angry or pouting",
    ":'(-|‑)?\(":"Crying",
    ":'(-|‑)?\)":"Tears of happiness",
    "D‑':":"Horror",
    "D:<":"Disgust",
    "D:":"Sadness",
    "D(8|;|=|X)":"Great dismay",
    ":(-|‑)?(O|o)":"Surprise",
    ":(-|‑)?0":"Shock",
    "8‑0":"Yawn",
    ">:O":"Yawn",
    ":(-|‑)?\*":"Kiss",
    ":X":"Kiss",
    "(;|\*)(-|‑)?\)":"Wink or smirk",
    ";(-|‑)?\]":"Wink or smirk",
    ";\^\)":"Wink or smirk",
    ":‑,":"Wink or smirk",
    ";D":"Wink or smirk",
    "(:|X)(-|‑)?P":"Tongue sticking out, cheeky, playful or blowing a raspberry",
    ":(-|‑)?Þ":"Tongue sticking out, cheeky, playful or blowing a raspberry",
    ":(-|‑)?b":"Tongue sticking out, cheeky, playful or blowing a raspberry",
    "d:":"Tongue sticking out, cheeky, playful or blowing a raspberry",
    "=p":"Tongue sticking out, cheeky, playful or blowing a raspberry",
    ">:P":"Tongue sticking out, cheeky, playful or blowing a raspberry",
    ":(-|‑)?\/":"Skeptical, annoyed, undecided, uneasy or hesitant",
    ":-\[\.\]":"Skeptical, annoyed, undecided, uneasy or hesitant",
    r"(>?:|=)\[\(\\\)\]":"Skeptical, annoyed, undecided, uneasy or hesitant",
    "(>:|=)\/":"Skeptical, annoyed, undecided, uneasy or hesitant",
    ":(L|S)":"Skeptical, annoyed, undecided, uneasy or hesitant",
    "=L":"Skeptical, annoyed, undecided, uneasy or hesitant",
    ":(-|‑)?\|":"Straight face",
    ":\$":"Embarrassed or blushing",
    ":(-|‑)?(x|#|&)":"Sealed lips or wearing braces or tongue-tied",
    "O:(-|‑)?\)":"Angel, saint or innocent",
    "0:(-|‑)?(\)|3)":"Angel, saint or innocent",
    "0;\^\)":"Angel, saint or innocent",
    "(>|\}|3):(-|‑)?\)":"Evil or devilish",
    ">;\)":"Evil or devilish",
    "\|;‑\)":"Cool",
    "\|‑O":"Bored",
    ":‑J":"Tongue-in-cheek",
    "#‑\)":"Party all night",
    "%(-|‑)?\)":"Drunk or confused",
    ":(-|‑)?#{3}\.{2}":"Being sick",
    "<:‑\|":"Dump",
    "\(>_<\)>?":"Troubled",
    "\(';'\)":"Baby",
    "\(\^\^>``":"Nervous or Embarrassed or Troubled or Shy or Sweat drop",
    "\(\^_\^;\)":"Nervous or Embarrassed or Troubled or Shy or Sweat drop",
    "\(-_-;\)":"Nervous or Embarrassed or Troubled or Shy or Sweat drop",
    "\(~_~;\) \(・\.・;\)":"Nervous or Embarrassed or Troubled or Shy or Sweat drop",
    "\(-_-\)z{3}":"Sleeping",
    "\(\^_-\)":"Wink",
    "\(\(\+_\+\)\)":"Confused",
    "\(\+o\+\)":"Confused",
    "\(o\|o\)":"Ultraman",
    "\^_\^":"Joyful",
    "\(\^_\^\)\/":"Joyful",
    "\(\^(O|o)\^\)／":"Joyful",
    "\(__\)":"Kowtow as a sign of respect, or dogeza for apology",
    "_\(\._\.\)_":"Kowtow as a sign of respect, or dogeza for apology",
    "<\(_ _\)>":"Kowtow as a sign of respect, or dogeza for apology",
    "<m\(__\)m>":"Kowtow as a sign of respect, or dogeza for apology",
    "m\(__\)m":"Kowtow as a sign of respect, or dogeza for apology",
    "m\(_ _\)m":"Kowtow as a sign of respect, or dogeza for apology",
    "\('_'\)":"Sad or Crying",
    "\(\/_;\)":"Sad or Crying",
    "\(T_T\) \(;_;\)":"Sad or Crying",
    "\(;_;":"Sad or Crying",
    "\((;_:|;O;|:_;|ToT)\)":"Sad or Crying",
    ";(-|‑|n)?;":"Sad or Crying",
    "Q(\.|_)?Q":"Sad or Crying",
    "T\.T":"Sad or Crying",
    "\(-(\.|_)-\)":"Shame",
    "\(一一\)":"Shame",
    "\(；一_一\)":"Shame",
    "\(=_=\)":"Tired",
    "\(=\^·\^=\)":"Cat",
    "\(=\^··\^=\)":"Cat",
    "=_\^=":"Cat",
    "\(\._?\.\)":"Looking down",
    "\^m\^":"Giggling with hand covering mouth",
    "\(・・\?":"Confusion",
    "\(\?_\?\)":"Confusion",
    ">\^_\^<":"Normal Laugh",
    "<\^!\^>":"Normal Laugh",
    "\^\/\^":"Normal Laugh",
    "（\*\^_\^\*）":"Normal Laugh",
    "\(\^<\^\) \(\^\.\^\)":"Normal Laugh",
    "\(\^(\.|J|—|-)?\^\)":"Normal Laugh",
    "\(\^_\^\.?\)":"Normal Laugh",
    "\(\*\^\.\^\*\)":"Normal Laugh",
    "\(\^—\^）":"Normal Laugh",
    "\(#\^\.\^#\)":"Normal Laugh",
    "（\^—\^）":"Waving",
    "\(;_;\)\/~{3}":"Waving",
    "\(\^\.\^\)\/~{3}":"Waving",
    "\(-_-\)\/~{3} \(\$·{2}\)\/~{3}":"Waving",
    "\(T(_|o)T\)\/~{3}":"Waving",
    "\(\*\^0\^\*\)":"Excited",
    "\(\*_\*(\)|;)":"Amazed",
    "\(\+_\+\) \(@_@\)":"Amazed",
    "\(\*\^\^\)v":"Laughing,Cheerful",
    "\(\^_\^\)v":"Laughing,Cheerful",
    "\(\(d\[-_-\]b\)\)":"Headphones,Listening to music",
    '\(-"-\)':"Worried",
    "\(ーー;\)":"Worried",
    "\(\^0_0\^\)":"Eyeglasses",
    "\(＾(ｖ|ｕ)＾\)":"Happy",
    "\(\^\)o\(\^\)":"Happy",
    "\(\^(O|o)\^\)":"Happy",
    "\)\^o\^\(":"Happy",
    ":O o_O":"Surprised",
    "o_0":"Surprised",
    "o\.?O":"Surprised",
    "\(o\.o\)":"Surprised",
    "\(\*￣m￣\)":"Dissatisfied",
    "\(‘A`\)":"Snubbed or Deflated"
}
POS_EMOT = [
    r'.*(happy).*', r'.*(laugh).*', r'.*(happiness).*', r'.*(surprise).*',
    r'.*(kiss).*', r'.*(wink).*', r'.*(tongue)(?!-tied).*', r'.*(angel).*',
    r'.*(cool).*', r'.*(party).*', r'.*(baby).*', r'.*(sleeping).*',
    r'.*(confused).*', r'.*(ultraman).*', r'.*(joyful).*', r'.*(waving).*',
    r'.*(excited).*', r'.*(amazed).*', r'.*(headphones).*', r'.*(eyeglasses).*'
]
NEG_EMOT = [
    r'.*(sad).*', r'.*(crying).*', r'.*(horror).*', r'.*(disgust).*',
    r'.*(dismay).*', r'.*(shock).*', r'.*(yawn).*', r'.*(skeptical).*',
    r'.*(straight face).*', r'.*(embarrassed).*', r'.*(sealed lips).*',
    r'.*(evil).*', r'.*(bored).*', r'.*(sick).*', r'.*(dump).*',
    r'.*(troubled).*', r'.*(shame).*', r'.*(tired).*', r'.*(worried).*',
    r'.*(dissatisfied).*', r'.*(snubbed).*', r'.*(nervous).*', r'.*(confusion).*'
]

POS_EMOJI = [
    '\U0001F601', '\U0001F602', '\U0001F603', '\U0001F604', '\U0001F605',
    '\U0001F606', '\U0001F609', '\U0001F60A', '\U0001F60B', '\U0001F60C',
    '\U0001F60D', '\U0001F60F', '\U0001F618', '\U0001F61A', '\U0001F61C',
    '\U0001F61D', '\U0001F64C', '\U0001F600', '\U0001F607', '\U0001F60E',
    '\U0001F525', '\U0001F44D', '\U0001F4AA', '\U0001F4AF'
    ]
NEG_EMOJI = [
    '\U0001F612', '\U0001F613', '\U0001F614', '\U0001F616', '\U0001F61E',
    '\U0001F620', '\U0001F621', '\U0001F622', '\U0001F623', '\U0001F624',
    '\U0001F625', '\U0001F628', '\U0001F629', '\U0001F62A', '\U0001F62B',
    '\U0001F62D', '\U0001F630', '\U0001F631', '\U0001F632', '\U0001F633',
    '\U0001F635', '\U0001F637', '\U0001F645', '\U0001F610', '\U0001F611',
    '\U0001F615', '\U0001F61F', '\U0001F626', '\U0001F627', '\U0001F4A9', 
    '\U0001F44E'
    ]

SLANG = {
    'AFAIK': 'As Far As I Know',
    'AFK': 'Away From Keyboard',
    'ASAP': 'As Soon As Possible',
    'ATK': 'At The Keyboard',
    'ATM': 'At The Moment',
    'A3': 'Anytime, Anywhere, Anyplace',
    'BAK': 'Back At Keyboard',
    'BBL': 'Be Back Later',
    'BBS': 'Be Back Soon',
    'BFN': 'Bye For Now',
    'B4N': 'Bye For Now',
    'BRB': 'Be Right Back',
    'BRT': 'Be Right There',
    'BTW': 'By The Way',
    'B4': 'Before',
    'CU': 'See You',
    'CUL8R': 'See You Later',
    'CYA': 'See You',
    'FAQ': 'Frequently Asked Questions',
    'FC': 'Fingers Crossed',
    'FWIW': "For What It's Worth",
    'FYI': 'For Your Information',
    'GAL': 'Get A Life',
    'GG': 'Good Game',
    'GN': 'Good Night',
    'GMTA': 'Great Minds Think Alike',
    'GR8': 'Great!',
    'G9': 'Genius',
    'IC': 'I See',
    'ICQ': 'I Seek you',
    'ILU': 'ILU: I Love You',
    'IMHO': 'In My Honest Opinion',
    'IMO': 'In My Opinion',
    'IOW': 'In Other Words',
    'IRL': 'In Real Life',
    'KISS': 'Keep It Simple, Stupid',
    'LDR': 'Long Distance Relationship',
    'LMAO': 'Laugh My Aaa Off',
    'LOL': 'Laughing Out Loud',
    'LTNS': 'Long Time No See',
    'L8R': 'Later',
    'MTE': 'My Thoughts Exactly',
    'M8': 'Mate',
    'NRN': 'No Reply Necessary',
    'OIC': 'Oh I See',
    'PITA': 'Pain In The Ass',
    'PRT': 'Party',
    'PRW': 'Parents Are Watching',
    'ROFL': 'Rolling On The Floor Laughing',
    'ROFLOL': 'Rolling On The Floor Laughing Out Loud',
    'ROTFLMAO': 'Rolling On The Floor Laughing My Ass Off',
    'SK8': 'Skate',
    'STATS': 'Your sex and age',
    'ASL': 'Age Sex Location',
    'THX': 'Thank You',
    'TTFN': 'Ta-Ta For Now!',
    'TTYL': 'Talk To You Later',
    'U': 'You',
    'U2': 'You Too',
    'U4E': 'Yours For Ever',
    'WB': 'Welcome Back',
    'WTF': 'What The Fuck',
    'WTG': 'Way To Go!',
    'WUF': 'Where Are You From?',
    'W8': 'Wait'
    }